version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  # Fetch and update latest Docker images
  - package-ecosystem: docker
    directory: "/containers"
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
    open-pull-requests-limit: 10
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
